apiVersion: v1
kind: Service
metadata:
  name:  ms-frontend-http
  namespace: default
spec:
  selector:
    app: ms-frontend
  type: NodePort
  ports:
  - name: ms-frontend
    port: 80
    targetPort: 3000
    protocol: TCP
    

